import type { Ticket, Message, DashboardMetrics } from '../types';

export const mockTickets: Ticket[] = [
  {
    id: '1',
    title: 'Cannot login to my account',
    description: 'I am unable to login to my account. I keep getting an error message saying my password is incorrect, but I am sure it is correct.',
    userId: '4',
    assignedToId: '2',
    categoryId: '1',
    priorityId: '3',
    statusId: '2',
    createdAt: new Date('2024-12-15T08:00:00Z'),
    updatedAt: new Date('2024-12-15T10:30:00Z'),
    tags: ['login', 'password'],
    attachments: [],
  },
  {
    id: '2',
    title: 'Feature request: Dark mode',
    description: 'It would be great if the application had a dark mode option for better usability in low-light conditions.',
    userId: '5',
    assignedToId: '3',
    categoryId: '3',
    priorityId: '2',
    statusId: '1',
    createdAt: new Date('2024-12-14T14:20:00Z'),
    updatedAt: new Date('2024-12-14T14:20:00Z'),
    tags: ['ui', 'enhancement'],
    attachments: [],
  },
  {
    id: '3',
    title: 'Billing discrepancy',
    description: 'There seems to be an error in my last invoice. I was charged twice for the same service.',
    userId: '4',
    assignedToId: '2',
    categoryId: '2',
    priorityId: '3',
    statusId: '4',
    createdAt: new Date('2024-12-13T16:45:00Z'),
    updatedAt: new Date('2024-12-14T09:15:00Z'),
    tags: ['billing', 'invoice'],
    attachments: [],
  },
  {
    id: '4',
    title: 'App crashes on startup',
    description: 'The mobile app crashes immediately when I try to open it. This started happening after the latest update.',
    userId: '5',
    assignedToId: '3',
    categoryId: '4',
    priorityId: '4',
    statusId: '1',
    createdAt: new Date('2024-12-15T11:30:00Z'),
    updatedAt: new Date('2024-12-15T11:30:00Z'),
    tags: ['mobile', 'crash', 'bug'],
    attachments: [],
  },
  {
    id: '5',
    title: 'Password reset not working',
    description: 'I tried to reset my password multiple times but I never receive the reset email. I checked my spam folder as well.',
    userId: '4',
    categoryId: '1',
    priorityId: '2',
    statusId: '1',
    createdAt: new Date('2024-12-14T09:15:00Z'),
    updatedAt: new Date('2024-12-14T09:15:00Z'),
    tags: ['password', 'email', 'reset'],
    attachments: [],
  },
  {
    id: '6',
    title: 'Request for API documentation',
    description: 'Could you please provide detailed API documentation? I need to integrate with our internal systems.',
    userId: '5',
    assignedToId: '2',
    categoryId: '5',
    priorityId: '2',
    statusId: '2',
    createdAt: new Date('2024-12-13T14:20:00Z'),
    updatedAt: new Date('2024-12-14T10:30:00Z'),
    tags: ['api', 'documentation', 'integration'],
    attachments: [],
  },
];

export const mockMessages: Message[] = [
  {
    id: '1',
    ticketId: '1',
    userId: '4',
    content: 'I have tried resetting my password multiple times but the issue persists.',
    isInternal: false,
    createdAt: new Date('2024-12-15T08:15:00Z'),
  },
  {
    id: '2',
    ticketId: '1',
    userId: '2',
    content: 'Hi John, I can see your account is locked due to multiple failed login attempts. Let me unlock it for you.',
    isInternal: false,
    createdAt: new Date('2024-12-15T09:00:00Z'),
  },
  {
    id: '3',
    ticketId: '1',
    userId: '2',
    content: 'Account has been unlocked. Customer should be able to login now.',
    isInternal: true,
    createdAt: new Date('2024-12-15T09:05:00Z'),
  },
  {
    id: '4',
    ticketId: '1',
    userId: '4',
    content: 'Thank you! I can login now.',
    isInternal: false,
    createdAt: new Date('2024-12-15T10:30:00Z'),
  },
  {
    id: '5',
    ticketId: '3',
    userId: '2',
    content: 'I have reviewed your invoice and confirmed the duplicate charge. A refund has been processed and should appear in your account within 3-5 business days.',
    isInternal: false,
    createdAt: new Date('2024-12-14T09:15:00Z'),
  },
];

export const mockDashboardMetrics: DashboardMetrics = {
  totalTickets: 156,
  openTickets: 23,
  pendingTickets: 8,
  resolvedTickets: 125,
  avgResolutionTime: 4.2, // hours
  ticketTrends: [
    { date: '2024-12-09', opened: 12, resolved: 8 },
    { date: '2024-12-10', opened: 15, resolved: 11 },
    { date: '2024-12-11', opened: 8, resolved: 14 },
    { date: '2024-12-12', opened: 18, resolved: 12 },
    { date: '2024-12-13', opened: 14, resolved: 16 },
    { date: '2024-12-14', opened: 11, resolved: 9 },
    { date: '2024-12-15', opened: 7, resolved: 13 },
  ],
  categoryDistribution: [
    { categoryId: '1', count: 45 },
    { categoryId: '2', count: 28 },
    { categoryId: '3', count: 22 },
    { categoryId: '4', count: 38 },
    { categoryId: '5', count: 23 },
  ],
};