import type { User } from '../types';

export const mockUsers: User[] = [
  {
    id: '1',
    email: 'admin@helpdesk.com',
    firstName: 'Admin',
    lastName: 'User',
    role: 'admin',
    avatar: 'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=150',
    createdAt: new Date('2024-01-01'),
    isActive: true,
  },
  {
    id: '2',
    email: 'agent@helpdesk.com',
    firstName: 'Sarah',
    lastName: 'Johnson',
    role: 'agent',
    avatar: 'https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg?auto=compress&cs=tinysrgb&w=150',
    createdAt: new Date('2024-01-15'),
    isActive: true,
  },
  {
    id: '3',
    email: 'agent2@helpdesk.com',
    firstName: 'Mike',
    lastName: 'Chen',
    role: 'agent',
    avatar: 'https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=150',
    createdAt: new Date('2024-01-20'),
    isActive: true,
  },
  {
    id: '4',
    email: 'user@example.com',
    firstName: 'John',
    lastName: 'Doe',
    role: 'user',
    avatar: 'https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=150',
    createdAt: new Date('2024-02-01'),
    isActive: true,
  },
  {
    id: '5',
    email: 'user2@example.com',
    firstName: 'Emma',
    lastName: 'Wilson',
    role: 'user',
    avatar: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=150',
    createdAt: new Date('2024-02-05'),
    isActive: true,
  },
];